POST https://44dad13dwb.execute-api.us-east-1.amazonaws.com/v1/api/reminders/add HTTP/1.1
content-type: application/json

{
    "docId": "immigration|us#i94",
    "cid": "LtqCc253FcweDLI",    
    "expiresOn": "2036-01-22",
    "sendSMS": "true",
    "sendEmail": "true",
    "sendPush": "false",
    "sendWhatsapp": "false",
    "alsoCC": "false",
    "notes": "new notes: 1"
}

