POST https://44dad13dwb.execute-api.us-east-1.amazonaws.com/v1/api/reminders/update HTTP/1.1
content-type: application/json

{
    "id": "eBhVBP6v27AIH4k",
    "cid": "LtqCc253FcweDLI",    
    "date": "2026-09-25",
    "alsoCC": "true",
    "notes": "an update :3"
}