// @token (v6@) = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoia2tBR2lkdFl4SUdtM2VMIiwiaWF0IjoxNzEwOTU2NTUyLCJleHAiOjE3MTEwNDI5NTJ9.-nHVhtF33zQKfuRhu0cY4Df-fDhVtiJsPPbgFl8OSAQ
// @token (v7@) = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiOG9MSE9jQmp5TlhqU0hKIiwiaWF0IjoxNzEwOTU3MDY5LCJleHAiOjE3MTA5NjA2Njl9.R0MnPb0VoDGQoOQiywgNmJPFqWJiAKCrZta_APhoZhE
// @email = m.v6@gmail.com

@ep = 77uxp6az23.execute-api.us-east-1.amazonaws.com/v1/api

POST https://{{ep}}/customer/register
    ?email=m.v8@gmail.com
    &token=abcde HTTP/1.1
content-type: application/json

{
}


###


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiM2JITWVMSWxFWFBpa0tDIiwiaWF0IjoxNzEwOTU5NjU1LCJleHAiOjE3MTEwNDYwNTV9.au0zL_MSTcHMf35CqGUVIkjG2b5rigo9CLFmim14Slw
@email = m.v8@gmail.com

POST https://77uxp6az23.execute-api.us-east-1.amazonaws.com/v1/api/customer/verify?email={{email}}&token={{token}} HTTP/1.1
content-type: application/json

{
}


###

POST https://{{ep}}/customer/update?token={{token}}  HTTP/1.1
content-type: application/json

{
    "nickName": "Slartibarfast",
    "cellNumber": "+1732-599-5930",
    "countryCode": "us",
    "stateCode": "wa",
    "sendEmail": "true",
    "sendSMS": "true",
    "sendWhatsapp": "false",
    "sendMarketingEmails": "false",
    "sendTopicUpdates": "false",
    "sendPush": "false",
    "ccOnByDefault": "true",
    "emailCC": ["ghiga@shunga.com", "shuga@binga.com"]
}