// sample values
@ep = t3lzadbhf4.execute-api.us-east-1.amazonaws.com/v1
@email = owd.test.2@gmail.com
@key = OWD-202

POST https://{{ep}}/api/services/templated-email?key={{key}} HTTP/1.1
content-type: application/json

{
    "to": "m.venugopal@gmail.com",
    "templateName": "owd-reminder-record",
    "data": {
        "event": "Passport",
        "date": "12th Fri 2027",
        "notes": "For Jenny",
        "name": "subscriber",
        "entries": "12th Fri 2204<br>29th Oct 2029<br>"
    }
}

###

POST https://{{ep}}/api/services/add-notice?key={{key}} HTTP/1.1
content-type: application/json

{
    "to": "m.venugopal@gmail.com",
    "templateName": "owd-reminder-record",
    "data": {
        "event": "Passport",
        "date": "12th Fri 2027",
        "notes": "For Jenny",
        "name": "subscriber",
        "entries": "12th Fri 2204<br>29th Oct 2029<br>"
    }
}


