// @token (v6@) = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoia2tBR2lkdFl4SUdtM2VMIiwiaWF0IjoxNzEwOTU2NTUyLCJleHAiOjE3MTEwNDI5NTJ9.-nHVhtF33zQKfuRhu0cY4Df-fDhVtiJsPPbgFl8OSAQ
// @token (v7@) = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiOG9MSE9jQmp5TlhqU0hKIiwiaWF0IjoxNzEwOTU3MDY5LCJleHAiOjE3MTA5NjA2Njl9.R0MnPb0VoDGQoOQiywgNmJPFqWJiAKCrZta_APhoZhE
// @email = m.v6@gmail.com

// updated v2.0 reminder management API, uses HTTP methods rather than
// internal commands
// API source map: /v1/reminders/
// +-------+---------+-----+-------+-----------------------+
// | HTTP  | Op      | Web | Email | Notes                 |
// +-------+---------+-----+-------+-----------------------+
// | POST  | ADD     |  x  |       | new parent            |
// +-------+---------+-----+-------+-----------------------+
// | PUT   | INSERT  |  x  |       | new child             |
// +-------+---------+-----+-------+-----------------------+
// | PATCH | UPDATE  |     |       | update existing       |
// +-------+---------+-----+-------+-----------------------+
// | GET   | REPORT  |     |       | reporting             |
// +-------+---------+-----+-------+-----------------------+
// | GET   | DUE     |     |       | next n or all parent  |
// +-------+---------+-----+-------+-----------------------+
// | GET   |   |     |       | children of parent    |
// +-------+---------+-----+-------+-----------------------+
// | DELETE| DELETE  |     |       | delete                |
// +-------+---------+-----+-------+-----------------------+

@ep =44dad13dwb.execute-api.us-east-1.amazonaws.com/v1/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiT1dELTIwMjQwMzI4LUc2QXl0Z050S2kyZkxDSSIsImlhdCI6MTcxMTU5Nzc2MiwiZXhwIjoxNzExNzcwNTYyfQ.JVkJQJP7xFtGBF5pKUvBsR2AE2IXZxsSxkfsqIdkFzk

@email = owd.test.1@gmail.com

@key = ABCDEFG

// ADD a new parent reminder for a document
// key is required for all operations (AWS key)
// response: 
//- 201 Created
//- 400 Bad Request
POST https://{{ep}}/reminders?key={{key}} HTTP/1.1
Authorization: {{token}}
content-type: application/json

{
    "docId": "travel|us#passport",
    "expiresOn": "2031-08-22",
    "sendSMS": "false",
    "sendEmail": "true",
    "sendPush": "true",
    "sendWhatsapp": "false",
    "alsoCC": "true",
    "notes": "for sara"
}

### 

// INSERT a child reminder for a parent 
// key is required for all operations (AWS key)
// response: 
//- 201 Created
//- 400 Bad Request
PUT https://{{ep}}/reminders?key={{key}} HTTP/1.1
Authorization: {{token}}
content-type: application/json

{
    "docId": "travel|us#passport",
    "expiresOn": "2029-03-22",
    "sendSMS": "false",
    "sendEmail": "true",
    "sendPush": "false",
    "sendWhatsapp": "false",
    "alsoCC": "false",
    "notes": "for sara"
}


###

// UPDATE an existing child reminder
// response: 
//- 201 Successful
//- 400 Bad Request
@id = cSmc-gQWzayK47d
PATCH https://{{ep}}/reminders?id={{id}}&key={{key}} HTTP/1.1
Authorization: {{token}}
content-type: application/json

{
    "docId": "travel|us#passport",
    "date": "2030-10-11"
}


###

// DELETE a specific parent or child reminder. 
// If the id is a parent, all children are deleted.
// response: 
//- 201 Successful
//- 404 Not Found
//- 400 Bad Request
// delete a specific notice by id
DELETE https://{{ep}}/reminders?id={{id}}&key={{key}} HTTP/1.1
Authorization: {{token}}
content-type: application/json

{
}


###

// GET the next n deadlines for a customer
// /parents only returns all parents
// /parents/12345 returns all children of parent 12345
// response:
//- 200 OK
//- 400 Bad Request
//- 404 Not Found (no reminders)

GET https://{{ep}}/reminders/parents?limit=25 HTTP/1.1
Authorization: {{token}}
content-type: application/json

{}

###


GET https://{{ep}}/reminders/parents/RINFcdO-NrrlnA4?limit=10 HTTP/1.1
Authorization: {{token}}
content-type: application/json