// @token (v6@) = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoia2tBR2lkdFl4SUdtM2VMIiwiaWF0IjoxNzEwOTU2NTUyLCJleHAiOjE3MTEwNDI5NTJ9.-nHVhtF33zQKfuRhu0cY4Df-fDhVtiJsPPbgFl8OSAQ
// @token (v7@) = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiOG9MSE9jQmp5TlhqU0hKIiwiaWF0IjoxNzEwOTU3MDY5LCJleHAiOjE3MTA5NjA2Njl9.R0MnPb0VoDGQoOQiywgNmJPFqWJiAKCrZta_APhoZhE
// @email = m.v6@gmail.com

@ep =44dad13dwb.execute-api.us-east-1.amazonaws.com/v1/api


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiM2JITWVMSWxFWFBpa0tDIiwiaWF0IjoxNzEwOTU5NjU1LCJleHAiOjE3MTEwNDYwNTV9.au0zL_MSTcHMf35CqGUVIkjG2b5rigo9CLFmim14Slw
@email = m.v8@gmail.com

// add a reminder
POST https://{{ep}}/reminders/add?email={{email}}&token={{token}} HTTP/1.1
content-type: application/json

{
    "docId": "travel|us#passport",
    "expiresOn": "2029-09-24",
    "sendSMS": "false",
    "sendEmail": "true",
    "sendPush": "false",
    "sendWhatsapp": "false",
    "alsoCC": "false",
    "notes": "yumm is samosa"
}


###

@id = rOPXee1FeRKkGOK
// delete a specific notice by id
POST https://{{ep}}/reminders/delete?email={{email}}&token={{token}}&id={{id}} HTTP/1.1
content-type: application/json

{
}



###

// update a specific notice by id
POST https://{{ep}}/reminders/update?email={{email}}&token={{token}}&id={{id}} HTTP/1.1
content-type: application/json


{
    "date": "2033-12-20",
    "alsoCC": "false",
    "notes": "an update :4"
}

###
GET https://{{ep}}/reminders/get?email={{email}}&token={{token}}&n=3 HTTP/1.1
content-type: application/json

{}
